### ISSUE TITLE
Submissions not working

### ISSUE THREAD

**Issue by Noellikecode** [manuarora700/react-code-editor#5]
I used your editor and put my own API key into it and it doesn't seem to be working, please help
CodeSandBox:
https://codesandbox.io/p/github/manuarora700/react-code-editor/csb-w0vsw6/draft/unruffled-nightingale?file=%2F.env.sample&selection=%5B%7B%22endColumn%22%3A77%2C%22endLineNumber%22%3A3%2C%22startColumn%22%3A77%2C%22startLineNumber%22%3A3%7D%5D

**Comment by manuarora700** [comment]
It's asking for permission.

**Comment by Noellikecode** [comment]
That's weird, try this link and let me know if it works. I put the permissions as anyone can edit.
https://codesandbox.io/p/github/manuarora700/react-code-editor/csb-w0vsw6/draft/unruffled-nightingale?file=%2F.env.sample&selection=%5B%7B%22endColumn%22%3A77%2C%22endLineNumber%22%3A3%2C%22startColumn%22%3A77%2C%22startLineNumber%22%3A3%7D%5D

**Comment by manuarora700** [comment]
Did you create a `.env` file and pasted the contents of `.env.sample` there?

**Comment by Noellikecode** [comment]
Ok I'll try that.

**Comment by Noellikecode** [comment]
It still doesn't work.

**Comment by manuarora700** [comment]
Double-check the `REACT_APP_RAPID_API_URL` key. There should be no `about` in the url.

**Comment by Noellikecode** [comment]
Still nothing, also you can edit if you want.

**Comment by manuarora700** [comment]
For judge0, select a pricing plan (the free one) to subscribe to the API. 
Right now, you're not subscribed and are getting the below error.

<img width="746" alt="Screenshot 2022-11-07 at 12 29 33 PM" src="https://user-images.githubusercontent.com/23276437/200245014-a00e3063-b516-4430-8553-b111fafcfade.png">

I've made the rest of the changes to your `.env` file and it should work.

**Comment by Noellikecode** [comment]
Thanks for solving my issue!
Also, one more thing, I made a new sandbox with the files in it, and I keep getting a "status not defined" error, so if you could check it out, that would be great.
https://codesandbox.io/s/withered-framework-jerl1k?
