### ISSUE TITLE
Code is Not Running.

### ISSUE THREAD

**Issue by mayankrajparmar** [manuarora700/react-code-editor#9]
I followed your instructions but still i am getting this error.
![Screenshot 2023-05-22 202010](https://github.com/manuarora700/react-code-editor/assets/68888262/c4b4372e-874b-4e90-bc41-fbbb4395f0fa)

https://github.com/manuarora700/react-code-editor/assets/68888262/01831635-15d0-4b85-916b-8762f311509a

Please Help Me.

**Comment by manuarora700** [comment]
Looks like an environment variables issue. Create the .env file and double check the credentials.

**Comment by mayankrajparmar** [comment]
Thank You Sir.
